name: Override env val # ワークフロー名
on: push # イベント
env:
  EXAMPLE: Defined by workflow
jobs: # ジョブ
  prints: # ジョブID
    runs-on: ubuntu-latest # ランナー　実行環境
    steps: # ステップ
      - run: echo "${EXAMPLE}"
      - env:
          EXAMPLE: Defined by step level
        run: echo ${{env.EXAMPLE}} | echo "${GITHUB_ACTION}" | echo "${GITHUB_ACTION_PATH}" | echo "${GITHUB_ACTION_REPOSITORY}"
