name: Sand Box For CI/CD # ワークフロー名
on: push # イベント
jobs: # ジョブ
  prints: # ジョブID
    name: This text is jobs name
    runs-on: ubuntu-latest # ランナー　実行環境
    permissions:
      contents: read
    steps: # ステップ
      - name: Check out
        uses: actions/checkout@v4
      - name: This text is steps name2
        run: gh repo list
        env:
          TOKEN: ${{secrets.GITHUB_TOKEN}}
