name: Bash tracing # ワークフロー名
on: push # イベント
jobs: # ジョブ
  logs: # ジョブID
    name: This text is jobs name
    runs-on: ubuntu-latest # ランナー　実行環境
    steps: # ステップ
      - name: Check out
        uses: actions/checkout@v4
      - run: |
          set -x
          date
          hostname
